Fix ld: error: undefined symbol: ceil on FreeBSD
When building on FreeBSD the compilation errors because it cannot find the math library. This single line links it.